# Generated by Django 5.1 on 2025-09-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='PerevalImageAsIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.TextField()),
            ],
            options={
                'db_table': 'pereval_images_as_is',
            },
        ),
        migrations.CreateModel(
            name='PerevalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fam', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('otc', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'pereval_users',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('other_titles', models.CharField(blank=True, max_length=500)),
                ('connect', models.CharField(blank=True, max_length=500)),
                ('add_time', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=8)),
                ('winter', models.CharField(blank=True, max_length=10)),
                ('spring', models.CharField(blank=True, max_length=10)),
                ('summer', models.CharField(blank=True, max_length=10)),
                ('autumn', models.CharField(blank=True, max_length=10)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalcoords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevaluser')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.perevaladded')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_link', to='api.perevalimageasis')),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
    ]
